name: build image and update VM
on:
  push:
    branches:
      - main
jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push job-finder
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ziyixi/job-finder:latest

      - name: Build and push sqlite-web
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.sqlite-web
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ziyixi/sqlite-web:latest

  update_vm:
    runs-on: ubuntu-latest
    needs: build-and-publish-image

    steps:
      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Docker Compose commands on Azure VM
        run: |
          az vm run-command invoke \
            --resource-group container-host \
            --name ContainerHostVM \
            --command-id RunShellScript \
            --scripts "su xiziyi -c 'cd /home/xiziyi/self-host-on-azure && git pull && chmod +x update.sh && ./update.sh > info 2>&1'" \
